import { NextRequest, NextResponse } from 'next/server'

/**
 * POST /api/screenshots
 * Generates a QR code URL for the app.
 * Screenshots are uploaded directly by the user from their Expo simulator,
 * not generated by AI — Apple requires real app screens.
 */
export async function POST(req: NextRequest) {
    try {
        const body = await req.json()
        const { session } = body

        const appName = session?.appName || session?.selectedName || 'app'

        // Generate QR code
        const qrCode = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(`https://${appName.toLowerCase().replace(/\s+/g, '')}.app`)}`

        return NextResponse.json({ qrCode })
    } catch (error: any) {
        console.error('[Screenshots API]', error)
        return NextResponse.json({ error: error.message }, { status: 500 })
    }
}
